# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: FlutterInstall@0
  displayName: "Install Flutter"
  inputs:
    channel: stable
    version: latest

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: full_access_adr_token
    appSlug: 'mahendra.patel03/FirstFlutterApp'
    appFile: 
    buildVersion: '1.0'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    destinationType: 'groups'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
